theme: jekyll-theme-cayman
show_downloads: true

# google_analytics:[Your Google Analytics tracking ID]

# Name of website
title: Energy-efficient cross-camera communication for overlapping FOV
description: Project for UCLA ECEM202A/CSM213A (Fall 2021)
